import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    Avatar,
    Badge,
    Button,
    Card,
    Container,
    Col,
    Row,
    Grid,
    Input,
    Switch,
    Progress,
    useTheme,
    Navbar,
    Text,
    Spacer,
} from '@nextui-org/react'
import { useTheme as useNextTheme } from 'next-themes'
import React from 'react'
import Character, { CharacterSkill, SkillTitle } from './character'
import { RiSunFill, RiMoonFill } from 'react-icons/ri'

import { SearchInput } from '../components/search_input'

const ButtonComponent = () => <Button>Click me</Button>

const Header = () => {
    const { setTheme } = useNextTheme()
    const { isDark } = useTheme()
    return (
        <>
            <Navbar variant="floating">
                <Navbar.Brand>
                    <Text
                        h1
                        size={30}
                        css={{
                            textGradient: '45deg, $blue600 -20%, $pink600 50%',
                        }}
                        weight="bold"
                    >
                        Dwarf&nbsp;
                    </Text>
                    <Text
                        h1
                        size={30}
                        css={{
                            textGradient:
                                '45deg, $purple600 -20%, $pink600 100%',
                        }}
                        weight="bold"
                    >
                        Bridge&nbsp;
                    </Text>
                    <Badge color={'warning'} size={'sm'}>
                        Pré-Alpha
                    </Badge>
                </Navbar.Brand>
                <Navbar.Content hideIn="xs">
                    <Navbar.Link isActive variant={'underline'} href="#">
                        Search
                    </Navbar.Link>
                    <Navbar.Link isDisabled href="#">
                        Characters<Badge size="xs">Soon</Badge>
                    </Navbar.Link>
                    <Navbar.Link isDisabled href="#">
                        Builds<Badge size="xs">Soon</Badge>
                    </Navbar.Link>
                    <Navbar.Link isDisabled href="#">
                        Wars<Badge size="xs">Soon</Badge>
                    </Navbar.Link>
                    <Navbar.Link isDisabled href="#">
                        Hunting Places
                        <Badge size="xs">Soon</Badge>
                    </Navbar.Link>
                </Navbar.Content>
                <Navbar.Content>
                    <Button
                        style={{
                            cursor: 'pointer',
                            background: 'transparent',
                            border: 'none',
                            padding: 0,
                            width: '32px',
                            minWidth: '32px',
                        }}
                        onPress={() => {
                            console.log('pressed')
                            setTheme(isDark ? 'light' : 'dark')
                        }}
                    >
                        {isDark ? (
                            <RiSunFill size={20}></RiSunFill>
                        ) : (
                            <RiMoonFill size={20} color={'black'}></RiMoonFill>
                        )}
                    </Button>
                    <Badge content="Soon" size="xs">
                        <Avatar>Soon</Avatar>
                    </Badge>
                </Navbar.Content>
            </Navbar>
        </>
    )
}

export default function HelloPage() {
    return (
        <Container>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header></Header>
            <Container
                alignItems="center"
                as="section"
                className="center__container"
                css={{
                    position: 'relative',
                    // height: '100%',
                    height: 'calc(70vh)',
                    // '@xsMax': {
                    //     height: 'calc(100vh - 64px)',
                    // },
                }}
                display="flex"
                // gap={0}
                // justify="space-between"
                // lg={true}
                // wrap="nowrap"
            >
                <Grid.Container>
                    <Grid xs={12} justify="center">
                        <SearchInput></SearchInput>
                    </Grid>
                </Grid.Container>
            </Container>

            {/* <Character></Character> */}
        </Container>
    )
}
