import { Head } from 'next/document'
import React from 'react'
import { Header } from '../components/header'

export interface Props {
    routes: string[]
    currentRoute?: string
    tag?: string
    slug?: string
}

const DefaultLayout: React.FC<React.PropsWithChildren<Props>> = ({
    children,
    routes,
}) => {
    return (
        <div id="app-container">
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <Header routes={routes}></Header>
            {children}
        </div>
    )
}

export default DefaultLayout
